services:
  learn-hanzi-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learn-hanzi-client
    working_dir: /app
    user: root
    ports:
      - "5173:5173"
    volumes:
      - ./:/app:z
      - learn-hanzi-client-node-modules:/app/node_modules
      - learn-hanzi-client-pnpm-store:/pnpm/store
    command: pnpm run dev --host 0.0.0.0 --port 5173

volumes:
  learn-hanzi-client-node-modules:
  learn-hanzi-client-pnpm-store:

